// Auto-generated by scripts/core_binaryize.mjs
// Fix 5: SHA-256 integrity verification before loading bytecode
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const bundlePath = path.join(__dirname, 'core-bin', 'core_bundle.jsc');
const hashPath = path.join(__dirname, 'core-bin', 'core_bundle.jsc.sha256');

let core;
if (fs.existsSync(bundlePath)) {
  // Verify integrity before loading bytecode
  let verified = false;
  if (fs.existsSync(hashPath)) {
    const expectedHash = fs.readFileSync(hashPath, 'utf8').trim().split(/\s+/)[0];
    const actualHash = crypto
      .createHash('sha256')
      .update(fs.readFileSync(bundlePath))
      .digest('hex');
    if (actualHash === expectedHash) {
      verified = true;
    } else {
      console.error('[core_binary] WARNING: .jsc hash mismatch! Expected:', expectedHash, 'Got:', actualHash);
      console.error('[core_binary] Falling back to source files. The binary may have been tampered with.');
    }
  } else {
    console.warn('[core_binary] No .sha256 hash file found. Falling back to source files.');
  }

  if (verified) {
    const require = createRequire(import.meta.url);
    require('bytenode');
    core = require('./core-bin/core_bundle.jsc');
  } else {
    core = await import('./core_source_exports.mjs');
  }
} else {
  core = await import('./core_source_exports.mjs');
}

export const autoClicker = core.autoClicker;
export const buttonProfileStore = core.buttonProfileStore;
export const screenWatcher = core.screenWatcher;
export const ocrDetector = core.ocrDetector;
