// Auto-generated by scripts/core_binaryize.mjs
import * as m0 from './core/auto_clicker.js';
import * as m1 from './core/button_profile_store.js';
import * as m2 from './core/screen_watcher.js';
import * as m3 from './core/ocr_detector.js';

export const autoClicker = m0.autoClicker;
export const buttonProfileStore = m1.buttonProfileStore;
export const screenWatcher = m2.screenWatcher;
export const ocrDetector = m3.ocrDetector;
